name: Docker Image CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  Prepare-env-and-load-vars:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
      repo: ${{ steps.vars.outputs.repo }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load version and repo variables
        id: vars
        run: |
          source DOCKER_VARS
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=repo::$DOCKER_REPO"

  conneting-to-Dockerhub:
    runs-on: ubuntu-latest
    needs: load-vars
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [load-vars, login]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.load-vars.outputs.repo }}:${{ needs.load-vars.outputs.version }}