name: ci-pipeline

on: push
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: set environment variables
        run: echo "DOCKER_REPO=your-dockerhub-repo" >> $GITHUB_ENV

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.VERSION }}